config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'organizer/new'
  post 'organizer/create'
  delete 'organizer/:id/' => 'organizer#destroy'

  resources :check_in
  post 'check_in/submit' =>  'tournaments#submit_list'

  get 'sponsors/new'
  #post 'charges/create'
  post 'sponsors/create'

  get 'sponsorships/new'
  post 'sponsorships/create'

  #for searching for golf courses
  get 'tournaments/update_courses' => 'tournaments#update_courses'
  get 'tournaments/update_hosts' => 'tournaments#update_hosts'
  get 'tournaments/:id/refund' => 'tournaments#refund'
  get 'tournaments/:id/resend_confirmation' => 'tournaments#resend_confirmation'
  post 'tournaments/:id/email' => 'tournaments#email'
  get 'tournaments/:id/delete_logo' => 'tournaments#delete_logo'
  post 'tournaments/:id/create_host' => 'tournaments#create_host'

  get 'scheduled_events/new'
  post 'scheduled_events/create'
  get 'unscheduled_events/new'
  post 'unscheduled_events/create'
  get 'photos/new'
  post 'photos/create'
  resources :tournaments do
   resources :scheduled_events, only: :destroy
   resources :unscheduled_events, only: :destroy
   resources :photos, only: :destroy
  end


  devise_for :people
  put 'people/update/:id' => 'people#update'


  get '/players/:id' => 'players#show'#, constraints: { id: /^[1-9][0-9]*$/ }

  get 'players/new'
  post 'players/create'

  get 'teams/:id' => 'teams#show'

  #ME FIX
  get 'people/:id' => 'people#show'#, constraints: { id: /^[1-9][0-9]*$/ }
  get 'people' => 'people#index'


  get 'welcome/index'

  #Rabachi: for the static pages
  get "/misc_pages/:misc_page" => "misc_pages#show"

  get 'tournaments/:id/organize' => "tournaments#organize"
  get 'tournaments/:id/checkin' => "tournaments#checkin"

  #for private tournaments
  controller :tournaments do
    get 'tournaments/:id/private/:key'     => :private_url
  end

  resources :golf_courses
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Mailer Stuff
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  post '/tournaments/invite' => "tournaments#invite"
  post '/tournaments/sms' => "tournaments#sms"

  #payments
  resources :charges
  #ZS: added sponsorship resources to create the default routes
#  resources :sponsorships


  # saves a golf course after model validation
  # post '/create_golf_course', to: 'golf_courses#create_golf_course'

  #Last Chance, all errors
  get "*any", via: :all, to: "errors#not_found"

end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         # Might need these later
         # ,:confirmable, :lockable

  has_many :players
  has_many :organizers
  mount_uploader :profilePicLink, PhotoUploader

  #Rabachi: for TOS agreement checking
  validates :terms_of_service, acceptance: true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  #show all the player's on our database
  def list
    @players = Person.all
    @people = Person.all
  end

  def index
  @people = Person.all
  @count = Person.count
  @person = Person.new
    #@tournaments.each do |t|
    # @addresses.push(get_golf_course_address(t))
    #end
  end

  def update
    @person = Person.find(params[:id])
    @person.update(params.require(:person).permit(:fName, :lName, :birthDate, :twitterLink, :fbLink, :profilePicLink))

    redirect_to :action => 'show'
  end

  #show a single player's profile based on passed in id
  def show
    @player_id = params[:id].to_i

    if @player_id == 0
      @player = Person.find(1)
      @player_id = 1
    else
      @player = Person.find(@player_id)
    end

    @golf_course_people = GolfCoursePerson.where(person_id:@player_id)
    if @golf_course_people.size>0

      golf_courses = []
      print('@golf_course_people EXISTS!');
    #   need two tabs for this: golf courses && hosted tournaments
      @golf_course_people.each do |golf_course_person|
          golf_courses << golf_course_person.golf_course_id
      end

      @golf_courses = GolfCourse.where(id:golf_courses)
      @tournaments_golf_courses = Tournament.where(golf_course_id:golf_courses)

    end
    @organizers = Organizer.where(person_id:@player_id)
    if @organizers.size > 0

      tournaments_organizers = []
      print('@organizers EXISTS!');
      @organizers.each do |organizer|
        tournaments_organizers << organizer.tournament_id
      end

      @tournaments_organizers = Tournament.where(id:tournaments_organizers)

    end
    @players = Player.where(person_id:@player_id)
    if  @players.size > 0

      tournaments_players = []
      print('@players  EXISTS!');
      @players.each do |player|
        tournaments_players << player.tournament_id
      end

      @tournaments_players = Tournament.where(id:tournaments_players)

    end
    @sponsors = Sponsor.where(person_id:@player_id)
    if @sponsors.size > 0

      tournaments_sponsors = []
      @sponsors.each do |sponsor|
        tournaments_sponsors << sponsor.tournament_id
      end

      @tournaments_sponsors = Tournament.where(id:tournaments_sponsors)
    end
  end
end

app/views/people/_edit.html.erb
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Let's start with the basic details</h4>
			</div>
			<div class="modal-body text-justify">
				<%= form_for @player, url: {:controller =>'people', :action => 'update'}, method:'put' do |t| %>
				<div class="container">
					<div class="row col-md-offset-0">
						<h4> My Information:</h4>
					</div>
					<br>
					<div class="row">
						<div class="col-md-4 col-md-offset-1">
                <%= t.label :fName, "First Name:" %>
				        <%= t.text_field(:fName, class: 'form-control')%>
                <br>

                <%= t.label :lName, "Last Name:" %>
				        <%= t.text_field(:lName, class: 'form-control')%>
                <br>

                <%= t.label :birthDate, "Birthday (YYYY-MM-DD):" %>
				        <%= t.text_field(:birthDate, class: 'form-control')%>
                <br>

                <%= t.label :twitterLink, "Twitter" %>
				        <%= t.text_field(:twitterLink, class: 'form-control')%>
                <br>

                <%= t.label :fbLink, "Facebook" %>
				        <%= t.text_field(:fbLink, class: 'form-control')%>
                <br>

                <%= t.label :profilePicLink, "Profile Picture:" %><br>
                <%= t.file_field :profilePicLink %>
                <br>
						</div>
					</div>
				</div>

				<div id = "submit" class="row">
					<div class="text-center">
						<button type = "submit" class ="btn btn-primary" %>
							Submit
						</button>
				</div>
			</div>
			<!--Hidden field to grab the person id-->
			<%= if (current_person != nil && current_person.id == @player.id) then t.hidden_field :person_id, :value => current_person.id end %>
			<% end %>
		</div>
		<div class="modal-footer">
			<!--empty now for spacing purposes-->
		</div>
	</div>
</div>
</div>

app/views/people/_golf_courses_tabs.erb
<% if golf_courses_passed_in != nil%>
    <% golf_courses_passed_in.each do |golf_course|%>
        <a href="http://<%= golf_course.websiteURL%>" class="list-group-item list-group-item-action">
          <!--sample item in the list-->
          <div class="row">
            <!--forst column of info-->
            <div class = "col-sm-6">
              <!--TODO: add timer for showing when registration ends-->
              <% if golf_course.name %>
                  <h4 class="list-group-item-heading"><%= golf_course.name %></h4>
                  <% if golf_course.email && golf_course.addrStreetNum && golf_course.addrStreetName && golf_course.addrPostalCode && golf_course.addrCountry%>
                      <p style="margin: 0"><%= golf_course.addrStreetNum %> <%= golf_course.addrStreetName %></p>
                      <p style="margin: 0"><%= golf_course.addrCountry %></p>
                      <p style="margin: 0"><%= golf_course.addrPostalCode %></p>
                  <% end %>
              <% end %>
            </div>
            <!--second column-->
            <div class = "col-sm-4">
              <% if golf_course.capacity && golf_course.email%>
                  <p style="margin: 0" class="list-group-item-text">Capacity: <%= golf_course.capacity%> players</p>
                  <p style="margin: 0" class="list-group-item-text">Email: <%= golf_course.email%></p>
              <% end %>
            </div>
            <!--TODO: missing dates and golf course due to data being omitted from the database -->
          </div>
        </a>
    <% end %>
<% else %>
    <div class="jumbotron" id = "google-maps-div">
      <p>No Tournaments in within the next Month. Please come back again!</p>
    </div>
<% end %>

app/views/people/_new.html.erb
<div class="modal fade" id="playerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">

  <% if person_signed_in? %>

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Play this tournament!</h4>
      </div>
      <div class="modal-body text-justify">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
          <%= form_for :player, url: {:controller =>'people', :action => 'create'}, method:'post' do |f| %>

            <%= f.label :'ticket_type_id' %><text class='text-danger'>*</text>
              <select name="player[ticket_type_id]" id="player_ticket_id_ticket_type_id" class="form-control">
                  <%= options_from_collection_for_select(@tournament.ticket_types, 'id', :select_option)%>
              </select>

            <%= f.label 'Quantity' %><text class='text-danger'>*</text><br>
            <%= f.number_field :'numTickets', min: 1, max: @tournament.ticketsLeft, step: 1, value: 1 %>
            <div>
            <br>
            <br>
            </div>

            <%= f.hidden_field :person_id, :value => current_person.id %>
            <%= f.hidden_field :tournament_id, :value => @tournament.id %>

            <!-- TODO: Gotta also not allow this continue if not paid-->

            <%= f.submit 'Proceed to Payment', class: 'btn btn-primary', id: 'add_player_btn'%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <!--empty now for spacing purposes-->
      </div>
    </div>

  <% else %>

    <div class="modal-content panel-danger">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">ERROR</h4>
        </div>
        <div class="modal-body">
          <h3>
          You must be signed in to become a player of this tournament
          </h3>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Okay</button>
        </div>
      </div>

  <% end %>

  </div>
</div>

app/views/people/_tournament_tabs.erb
<% if tournaments_passed_in != nil%>
    <% tournaments_passed_in.each do |tournament|%>
        <!-- TODO: BAD. HASH? NO -->
        <a href="/tournaments/<%= tournament.id %>" class="list-group-item list-group-item-action">
        
          <!--sample item in the list-->
          <div class="row">

            <!--first column image-->
            <div class = "col-sm-2">
              <% if tournament.logoLink %>
                  <%= cl_image_tag(tournament.logoLink, :width => 100, :height => 100, :crop => :fill,  :class => 'featurette-image img-circle img-responsive pull-left')%>
              <% end %>
            </div>

            <!--second column of info-->
            <div class = "col-sm-5">
              <!--TODO: add timer for showing when registration ends-->
              <% if tournament.name %>
                  <h4 class="list-group-item-heading"><%= tournament.name %></h4>
                  <% if tournament.tournamentDate %>
                      <p><%= tournament.tournamentDate.strftime("%d %B, %Y") %></p>
                    <% end %>
                  <!--For the golf course and the registration end time-->
                  <!--<% if tournament.tournamentDate!=nil %>-->
                      <!--<p><%= tournament.tournamentDate %></p>-->
                      <!--<% end %>-->
                  <!--<% if tournament.tournamentDate!=nil %>-->
                      <!--<p><%= tournament.tournamentDate %></p>-->
                      <!--<% end %>-->
              
                <% if tournament.numGuests %>
                    <p><%= tournament.numGuests - tournament.ticketsLeft %> players attending</p>
                <% end %>

              <% end %>
              <p class="list-group-item-text"></p>
            </div>

            <!--TODO: missing dates and golf course due to data being omitted from the database -->
            <div class = "col-sm-3">
              <% if tournament.golf_course %>
              
                <div id="map-container">
                  <div class="text-center">
                    <iframe frameborder="0" height="100px" style="border:0; text-align: left"
                        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDMbwpEJjsPHGYafnf9848Yw9LYoero6Ow&q=<%= 
        tournament.golf_course.addrStreetNum.to_s + ' ' + tournament.golf_course.addrStreetName + ' ' + tournament.golf_course.addrPostalCode
                        %>"
                        allowfullscreen>
                    </iframe>
                  </div>
                </div>
 <% end %>
            </div>
            <!--TODO: missing dates and golf course due to data being omitted from the database -->
          </div>
        </a>
    <% end %>
<% else %>
    <div class="jumbotron" id = "google-maps-div">
      <p>No Tournaments in within the next Month. Please come back again!</p>
    </div>
<% end %>

app/views/people/index.html.erb
<div class="container">

  <h1>Users</h1>
  <h3>There are currently <%= @count%> users enjoying cl0ud9.</h3>
  
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th>
        #
        </th>
        <th>
        </th>
        
        <th class="course">
          <div class="dates-container">
            Name
            <span class="arrow-link arrow-link-down"></span>
          </div>
        </th>
      
        <th class="phone">
          <div class="tournament-container">
            Contact
            <span class="arrow-link arrow-link-down"></span>
          </div>
        </th>
      
      </tr>
    </thead>

    <div class="col-xs-12" style="height:40px;"></div>
    
    <tbody>
      <% for ppl in @people %>
        <tr>
          <td><%= ppl.id %></td>
          <td><%=cl_image_tag(ppl.profilePicLink, :width => 40, :height => 40, :crop => :fill,  :class => 'featurette-image img-circle img-responsive pull-left')%></td>
          <td><a href="/people/<%= ppl.id %>"><%= ppl.lName %>, <%= ppl.fName %></a></td>
          <td><%= ppl.email %></td>
      <% end %>
    </tbody>
  </table>
</div>


      <!-- @course_address = golfcourse.addrStreetNum.to_s + ' ' + golfcourse.addrStreetName + ' ' + golfcourse.addrPostalCode
       -->
<!-- Map embedding coming soon ... -->

app/views/people/show.html.erb
<%= render partial: 'people/edit'%>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= javascript_include_tag ('player_show.js') %>
  <title>Profile page</title>

    <!--<%= debug @tournaments_golf_courses%>-->
    <!-- Bootstrap Core CSS -->


  <!-- BREAKS THE SITE, Add back in if you can fix the issues with the application view. <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous"> -->

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Bootstrap Core JavaScript -->
  
    <!-- Page Content -->
    <div class="container">
        <!-- Second Featurette -->
        <div class = "row">
          <div class="featurette col-md-9" id="services">
            <%= cl_image_tag(@player.profilePicLink, :width => 250, :height => 250, :crop => :fill, :class => 'featurette-image img-circle img-responsive pull-left')%>
            <h2 class="featurette-heading"><%= @player.fName %>
              <span class="text-muted"><%= @player.lName %></span>
            </h2>

            <p>Email: <span class="text-muted"><%= @player.email %></span> </p>
            <% if @player.birthDate %>
                <p>Birthday: <span class="text-muted"><%= @player.birthDate %></span></p>
            <%end%>
            <% if @player.twitterLink %>
                <p>Twitter Link: <span class="text-muted"><%= @player.twitterLink %></span></p>
            <%end%>

            <p><%= link_to cl_image_tag('logo-facebook.svg'), @player.fbLink %></p>

          </div>
          <div class="col-md-3">
            <div class="pull-right" style="padding-top: 25px;">
              <% if (current_person != nil && current_person.id == @player.id) %>
                <a href="#editModal" role="button" class="btn btn-primary" data-toggle="modal">Edit</a>
              <% end %>
              <%= if (current_person != nil && current_person.id == @player.id) then link_to 'Edit my email or password', edit_person_registration_path , :class => 'btn btn-primary' end %>
            </div>
          </div>
        </div>

        <hr class="featurette-divider">

      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs float-xs-left">
            <% if @golf_courses != nil && @golf_courses.size>0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-0">Your Golf Courses</a>
                </li>
            <%end%>
            <% if @tournaments_golf_courses != nil  && @tournaments_golf_courses.size > 0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-1" >Hosted Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_sponsors != nil && @tournaments_sponsors.size > 0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-2">Sponsored Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_players != nil && @tournaments_players.size >0%>
                <li class="nav-item" >
                  <a class="nav-link" id = "nav-3">Playing Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_organizers != nil && @tournaments_organizers.size > 0%>
                <li class="nav-item" >
                  <a class="nav-link" id = "nav-4">Organizing Tournaments</a>
                </li>
            <%end%>
          </ul>
        </div>
        <!--loop through and display the golf courses-->

            <div class="card-block" id = "card-0">
              <% if @golf_courses != nil && @golf_courses.size>0%>
                  <%= render partial: 'people/golf_courses_tabs', :locals => {golf_courses_passed_in:@golf_courses}%>
            <%end%>
            </div>

            <div class="card-block" id = "card-1">
              <% if @tournaments_golf_courses != nil  && @tournaments_golf_courses.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_golf_courses}%>
            <%end%>
            </div>
            <div class="card-block" id = "card-2">
              <% if @tournaments_sponsors != nil && @tournaments_sponsors.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_sponsors}%>
            <%end%>
            </div>
            <div class="card-block" id = "card-3">
              <% if @tournaments_players != nil && @tournaments_players.size >0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_players}%>
            <%end%>
            </div>

            <div class="card-block" id = "card-4">
              <% if @tournaments_organizers != nil && @tournaments_organizers.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_organizers}%>
            <%end%>

            </div>


      </div>
      <div class="jumbotron" id = "no-data">
        <p><%= if (current_person == nil || current_person.id != @player.id) then "This person is not playing in, sponsoring, organizing, or hosting any tournaments" else "You are not playing, sponsoring, organizing, or hosting any tournaments!" end %></p>
      </div>
    </div>