config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  get 'organizer/new'
  post 'organizer/create'
  delete 'organizer/:id/' => 'organizer#destroy'

  resources :check_in
  post 'check_in/submit' =>  'tournaments#submit_list'

  get 'sponsors/new'
  #post 'charges/create'
  post 'sponsors/create'

  get 'sponsorships/new'
  post 'sponsorships/create'

  #for searching for golf courses
  get 'tournaments/update_courses' => 'tournaments#update_courses'
  get 'tournaments/update_hosts' => 'tournaments#update_hosts'
  get 'tournaments/:id/refund' => 'tournaments#refund'
  get 'tournaments/:id/resend_confirmation' => 'tournaments#resend_confirmation'
  post 'tournaments/:id/email' => 'tournaments#email'
  get 'tournaments/:id/delete_logo' => 'tournaments#delete_logo'
  post 'tournaments/:id/create_host' => 'tournaments#create_host'

  get 'scheduled_events/new'
  post 'scheduled_events/create'
  get 'unscheduled_events/new'
  post 'unscheduled_events/create'
  get 'photos/new'
  post 'photos/create'
  resources :tournaments do
   resources :scheduled_events, only: :destroy
   resources :unscheduled_events, only: :destroy
   resources :photos, only: :destroy
  end


  devise_for :people
  put 'people/update/:id' => 'people#update'


  get '/players/:id' => 'players#show'#, constraints: { id: /^[1-9][0-9]*$/ }

  get 'players/new'
  post 'players/create'

  get 'teams/:id' => 'teams#show'

  #ME FIX
  get 'people/:id' => 'people#show'#, constraints: { id: /^[1-9][0-9]*$/ }
  get 'people' => 'people#index'


  get 'welcome/index'

  #Rabachi: for the static pages
  get "/misc_pages/:misc_page" => "misc_pages#show"

  get 'tournaments/:id/organize' => "tournaments#organize"
  get 'tournaments/:id/checkin' => "tournaments#checkin"

  #for private tournaments
  controller :tournaments do
    get 'tournaments/:id/private/:key'     => :private_url
  end

  resources :golf_courses
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Mailer Stuff
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  post '/tournaments/invite' => "tournaments#invite"
  post '/tournaments/sms' => "tournaments#sms"

  #payments
  resources :charges
  #ZS: added sponsorship resources to create the default routes
#  resources :sponsorships


  # saves a golf course after model validation
  # post '/create_golf_course', to: 'golf_courses#create_golf_course'

  #Last Chance, all errors
  get "*any", via: :all, to: "errors#not_found"

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :person
  belongs_to :tournament
  belongs_to :team
  belongs_to :ticket_type

  attr_accessor :numTickets

  validates :QRCodeStr, uniqueness: true, if: ':QRCodeStr.present?'

  after_create(on: :create) do |p|
  	#so that qr codes will be unique even if one person buys a number of tickets
  	p.QRCodeStr = p.person.email + p.id.to_s + p.ticket_type.name + p.tournament.name + DateTime.now.to_s
  	p.save
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  #show all the player's on our database
  def list
    @players = Person.all
  end

  #show a single player's profile based on passed in id
  def show
    @player_id = params[:id].to_i

    if @player_id == 0
      @player = Person.find(1)
      @player_id = 1
    else
      @player = Person.find(@player_id)
    end

    @golf_course_people = GolfCoursePerson.where(person_id:@player_id)
    if @golf_course_people.size>0

      golf_courses = []
      print('@golf_course_people EXISTS!');
    #   need two tabs for this: golf courses && hosted tournaments
      @golf_course_people.each do |golf_course_person|
          golf_courses << golf_course_person.golf_course_id
      end

      @golf_courses = GolfCourse.where(id:golf_courses)
      @tournaments_golf_courses = Tournament.where(golf_course_id:golf_courses)

    end
    @organizers = Organizer.where(person_id:@player_id)
    if @organizers.size > 0

      tournaments_organizers = []
      print('@organizers EXISTS!');
      @organizers.each do |organizer|
        tournaments_organizers << organizer.tournament_id
      end

      @tournaments_organizers = Tournament.where(id:tournaments)

    end
    @players = Player.where(person_id:@player_id)
    if  @players.size > 0

      tournaments_players = []
      print('@players  EXISTS!');
      @players.each do |player|
        tournaments_players << player.tournament_id
      end

      @tournaments_players = Tournament.where(id:tournaments_players)

    end
    @sponsors = Sponsor.where(person_id:@player_id)
    if @sponsors.size > 0

      tournaments_sponsors = []
      @sponsors.each do |sponsor|
        tournaments_sponsors << sponsor.tournament_id
      end

      @tournaments_sponsors = Tournament.where(id:tournaments_sponsors)
    end
  end

  def new
    @player = Player.new
  end

  def create
    params.permit!
    @tournament = Tournament.find(params[:player][:tournament_id])
    @player = Player.new(params[:player])
    @player.paid = false
    @numPlayersOnTicket = @player.ticket_type.numPlayers
    @numTickets = @player.numTickets.to_i
    @numPlayers = @numTickets * @numPlayersOnTicket
    price = (@player.ticket_type.price * 100 *@numTickets).to_i
    if (@numPlayersOnTicket * @numTickets > @tournament.ticketsLeft)
      flash[:danger] = 'There are not enough tickets remaining to fill your order'
    else
      @newPlayers = Array.new(@numPlayers){|i| i=Player.new(params[:player])};
      @allPlayersValid = true
      Player.transaction do
        @newPlayers.each do |nP|
          if not nP.save
            @allPlayersValid = false
            @errors = nP.errors.full_messages
            break
          end
        end
      end
      if not @allPlayersValid
        flash[:danger] = 'There was an error with your order: ' + @errors.to_s
      else
        assign_to_teams(@newPlayers, @tournament.id)
        require_payment(price)
        GeneralMailer.ticket_confirmation_email(@newPlayers).deliver!
        # flash.now for to make the flash disappear after a while
        flash[:success] = 'You have successfully joined this tournament.'
        @tournament.ticketsLeft -= @numPlayers
        @tournament.save
      end
    end
    puts "Player id: #{@player.id}"

    if @tournament.privateURL
      #redirect_to url_for(:controller => :charges , :action => :new, :player_id => @player.id, :sponsorshipType => @player.ticket_type) and return
      redirect_to url_for(:controller => :tournaments, :action => "private_url", :key => @tournament.private_url.key, :id => @tournament.id)
    else
      #redirect_to url_for(:controller => :charges , :action => :new, :player_id => @player.id, :sponsorshipType => @player.ticket_type) and return
      redirect_to @tournament
    end
    #redirect_to url_for(:controller => :charges , :action => :new,:sponsor_id => @sponsor.id,:sponsorshipType => @sponsor.sponsorshipType) and return
  end

  def edit
  end

  def update
  end

  def delete
  end

  def require_payment(price)
    charge = Stripe::Charge.create(
      :amount => price,
      :description => 'Rails Stripe customer',
      :source => params[:stripeToken],
      :currency => 'CAD'
      )

      @player.paid = true
      @player.save
      @newPlayers.each do |p|
        p.paid = true
        p.save
      end

      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to Tournament.find(params[:player][:tournament_id])
  end

  private
  def assign_to_teams(newPlayers, tournament_id)
    numFullTeams = newPlayers.length / 4
    if numFullTeams > 0
      newTeams = Array.new(numFullTeams){|i| i=Team.create(tournament_id: tournament_id, numPlayers: 4)}
      Team.transaction do
        if newTeams
          newTeams.each do |nt|
            Team.assign_next_tee_time(nt, tournament_id)
            nt.save
          end
        end
      end
      i = 0
      newTeams.each do |t|
        newPlayers[i..i+3].each do |p|
          p.team_id = t.id
          p.save
        end
        i+=4
      end
      newPlayers = newPlayers[i..-1]
    end

    if newPlayers.length > 0
      teams = Tournament.find(tournament_id).teams
      newPlayers.each do |p|
        team = teams.select {|t| t.numPlayers < 4}.first
        if team.nil?
          team = Team.create(tournament_id: tournament_id, numPlayers: 1)
          Team.assign_next_tee_time(team, tournament_id)
          team.save
          teams = Tournament.find(tournament_id).teams
        else
          team.numPlayers += 1
          team.save
        end
        p.team_id = team.id
        p.save
      end
    end
  end

  # private
  #   def get_golf_courses
  #     golf_course_ids = []
  #     golf_course_people = GolfCoursePerson.find_by(person_id: @player_id)
  #     if golf_course_people != nil
  #       if golf_course_people.size > 1
  #         golf_course_people.each do |golf_course_person|
  #           golf_course_ids << golf_course_person.golf_course_id
  #         end
  #       else
  #         golf_course_ids << golf_course_people.golf_course_id
  #       end
  #       golf_courses = GolfCourse.find_by(golf_course_id: golf_course_ids)
  #
  #       return golf_courses
  #     end
  #
  #     return 0
  #
  #   end

end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/players/_new.html.erb
<!-- Partial Page for Player _new.html.erb -->

<!-- Style Sheets *Quick CSS -->
<style>
  /* Padding - just for asthetics on Bootsnipp.com */
  body { margin-top:20px; }

  /* CSS for Credit Card Payment form */
  .credit-card-box .panel-title {
      display: inline;
      font-weight: bold;
  }
  .credit-card-box .form-control.error {
      border-color: red;
      outline: 0;
      box-shadow: inset 0 1px 1px rgba(0,0,0,0.075),0 0 8px rgba(255,0,0,0.6);
  }
  .credit-card-box label.error {
    font-weight: bold;
    color: red;
    padding: 2px 8px;
    margin-top: 2px;
  }
  .credit-card-box .payment-errors {
    font-weight: bold;
    color: red;
    padding: 2px 8px;
    margin-top: 2px;
  }
  .credit-card-box label {
      display: block;
  }
  /* The old "center div vertically" hack */
  .credit-card-box .display-table {
      display: table;
  }
  .credit-card-box .display-tr {
      display: table-row;
  }
  .credit-card-box .display-td {
      display: table-cell;
      vertical-align: middle;
      width: 50%;
  }
  /* Just looks nicer */
  .credit-card-box .panel-heading img {
      min-width: 180px;
  }
</style>

<!-- Start of Page Div -->
<div class="modal fade" id="playerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog">

  <!-- Signed In -->
  <% if person_signed_in? %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Play this tournament!</h4>
      </div>
      <div class="modal-body text-justify">
        <!-- Start of ROW  -->
        <div class="row">
          <div class="col-md-8 col-md-offset-2" style="padding-bottom:10%;padding-top:10%">
          <%= form_for :player, url: {:controller =>'players', :action => 'create'}, :html=>{:id => 'player-form'}, method:'post' do |f| %>

            <%= f.label :'ticket_type_id' %><text class='text-danger'>*</text>
              <select name="player[ticket_type_id]" id="player_ticket_id_ticket_type_id" class="form-control">
                  <%= options_from_collection_for_select(@tournament.ticket_types, 'id', :select_option)%>
              </select>

            <%= f.label 'Quantity' %><text class='text-danger'>*</text><br>
            <%= f.number_field :'numTickets', min: 1, max: @tournament.ticketsLeft, step: 1, value: 1, class: 'form-control' %>
            <%= f.hidden_field :person_id, :value => current_person.id %>
            <%= f.hidden_field :tournament_id, :value => @tournament.id %>


            <div>
              <p>    
              </p>
            </div>
            <!-- Payments Stuff -->
              <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
              <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Payment Details</h3>
                    <div class="display-td" >                            
                      <img class="img-responsive pull-right" src="http://i76.imgup.net/accepted_c22e0.png">
                    </div>
                </div>                    
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-xs-12">
                    <div class="form-group">
                      <label for="cardNumber">CARD NUMBER</label>
                        <div class="input-group">
                          <input 
                            type="tel"
                            class="form-control"
                            name="number"
                            placeholder="Valid Card Number"
                            data-stripe="number"
                            autocomplete="cc-number"
                            required autofocus 
                          />
                          <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                        </div>
                    </div>                            
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    <div class="form-group">
                      <label>
                      <span>EXPIRATION (MM/YY)</span>
                      <input type="text" size="2" data-stripe="exp_month"  name="expiry">
                      
                    <span> / </span>
                    <input type="text" size="2" data-stripe="exp_year" >
                    </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-5 col-md-5">
                    <div class="form-group">
                      <label for="cardCVC">CV CODE</label>
                        <input 
                          type="tel" 
                          class="form-control"
                          name="cvc"
                          data-stripe="cvc"
                          placeholder="CVC"
                          autocomplete="cc-csc"
                          required
                        />
                    </div>
                  </div>                        
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    <input type="button" class="submit" id = "sib2" value="Submit Payment"/>
                  </div>
                </div>
                <div class="row" style="display:none;">
                  <div class="col-xs-12">
                    <p class="payment-errors"></p>
                  </div>
                </div>
              </div>
            </div>            
              <!-- CREDIT CARD FORM ENDS HERE -->
            
            <!--  End of Payment Stuff -->
          <% end %>
          </div>
        </div>
        <!-- End of Row -->
      <!-- End of modal body -->
      </div>
      <div class="modal-footer">
        <!--empty now for spacing purposes-->
      </div>
    </div>

  <!-- NO One Signed In -->
  <% else %>
    <div class="modal-content panel-danger">
      <div class="modal-header panel-heading">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">ERROR</h4>
        </div>
        <div class="modal-body">
          <h3>
          You must be signed in to become a player of this tournament
          </h3>
        </div>
        <div class="modal-footer">
            <a href=<%=new_person_session_path %> class="btn btn-primary data-toggle=modal">Log In</a>
            <a href=<%=new_person_registration_path %> class="btn btn-primary data-toggle="modal">Sign Up</a>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
          </div>
      </div>
  <% end %>
  <!-- End of No One Signed In -->


  </div>
</div>
<!-- End of Page Div -->

<!-- JS  -->
  <!-- JQuery -->
<!--   <script   
    src="https://code.jquery.com/jquery-3.1.1.slim.js"   
    integrity="sha256-5i/mQ300M779N2OVDrl16lbohwXNUdzL/R2aVUXyXWA="   
    crossorigin="anonymous">
  </script>
 -->
<!-- <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
 -->  
  <!-- Form Js -->
<script>
  $(document).ready(function () {
    console.log("DOCUMENT> READY !!");
    var $player_form = $("#player-form")
    Stripe.setPublishableKey('pk_test_RgnPfafPCKHSojLKReicFHiz');

    $("#sib2").on('click',function (e) {
      console.log("Clicked submit!");
      // Request a token from Stripe:
      Stripe.card.createToken($player_form, stripeResponseHandler);
      // Prevent the form from being submitted:
    });

    function stripeResponseHandler(status, response) {
      // Grab the form:
      //var $player_form = $('#player-form');
      if (response.error) { // Problem!
        console.log("ERROR!");
      } else { // Token was created!
        // Get the token ID:
        var token = response.id;
        console.log("TOKEN: "+ token);
        // Insert the token ID into the form so it gets submitted to the server:
        $player_form.append($('<input type="hidden" name="stripeToken">').val(token));
        // Submit the form:
        $player_form.get(0).submit();
      }
    }
  });
</script>

app/views/players/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= javascript_include_tag ('player_show.js') %>
    <title>Profile page</title>

    <!--<%= debug @tournaments_golf_courses%>-->
    <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>
    <!-- Page Content -->
    <div class="container">
        <!-- Second Featurette -->
        <div class="featurette" id="services">
          <%= cl_image_tag(@player.profilePicLink, :width => 250, :height => 250, :crop => :fill, :class => 'featurette-image img-circle img-responsive pull-left')%>
            <h2 class="featurette-heading"><%= @player.fName %>
                <span class="text-muted"><%= @player.lName %></span>
            </h2>

            <p>Email: <span class="text-muted"><%= @player.email %></span> </p>
            <% if @player.birthDate %>
              <p>Your Birthday: <span class="text-muted"><%= @player.birthDate %></span></p>
            <%end%>
            <% if @player.twitterLink %>
              <p>Your Twitter Link: <span class="text-muted"><%= @player.twitterLink %></span></p>
            <%end%>

            <p><%= link_to cl_image_tag('logo-facebook.svg'), @player.fbLink %></p>

        </div>
        <hr class="featurette-divider">

      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs float-xs-left">
            <% if @golf_courses != nil && @golf_courses.size>0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-0">Your Golf Courses</a>
                </li>
            <%end%>
            <% if @tournaments_golf_courses != nil  && @tournaments_golf_courses.size > 0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-1" >Hosted Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_sponsors != nil && @tournaments_sponsors.size > 0%>
                <li class="nav-item">
                  <a class="nav-link" id = "nav-2">Sponsored Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_players != nil && @tournaments_players.size >0%>
                <li class="nav-item" >
                  <a class="nav-link" id = "nav-3">Playing Tournaments</a>
                </li>
            <%end%>
            <% if @tournaments_organizers != nil && @tournaments_organizers.size > 0%>
                <li class="nav-item" >
                  <a class="nav-link" id = "nav-4">Organizing Tournaments</a>
                </li>
            <%end%>
          </ul>
        </div>
        
        <!--loop through and display the golf courses-->

            <div class="card-block" id = "card-0">
              <% if @golf_courses != nil && @golf_courses.size>0%>
                  <%= render partial: 'people/golf_courses_tabs', :locals => {golf_courses_passed_in:@golf_courses}%>
            <%end%>
            </div>

            <div class="card-block" id = "card-1">
              <% if @tournaments_golf_courses != nil  && @tournaments_golf_courses.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_golf_courses}%>
            <%end%>
            </div>

            <div class="card-block" id = "card-2">
              <% if @tournaments_sponsors != nil && @tournaments_sponsors.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_sponsors}%>
            <%end%>
            </div>
            
            <div class="card-block" id = "card-3">
              <% if @tournaments_players != nil && @tournaments_players.size >0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_players}%>
            <%end%>
            </div>

            <div class="card-block" id = "card-4">
              <% if @tournaments_organizers != nil && @tournaments_organizers.size > 0%>
                  <%= render partial: 'people/tournament_tabs', :locals => {tournaments_passed_in:@tournaments_organizers}%>
            <%end%>

            </div>


      </div>
      <div class="jumbotron" id = "no-data">
        <p>You are not playing, sponsoring, organizing or hosting a tournament!</p>
      </div>
    </div>

</body>
</html>